[package]
name = "knock"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
dotenvy = "0.15.7"
openai = "1.0.0-alpha.16"
regex = "1.11.0"
reqwest = "0.12.8"
serde = "1.0.210"
serde_json = "1.0.132"
tokio = "1.40.0"
